apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-app-route
  namespace: default
spec:
  parentRefs:
    - name: gateway
      sectionName: web
    - name: gateway
      sectionName: websecure
  hostnames:
  # Used for testing with local cluster
    - "web-app.localhost"
  # Used for testing with Azure Cluster
    - "www.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web-app-1
          port: 80
